"""initial schema

Revision ID: 794487f7cd9e
Revises: 
Create Date: 2026-06-02 23:43:09.187108
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '794487f7cd9e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=48), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=96), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_run_id'), ['run_id'], unique=False)

    op.create_table('checkpoints',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoints_run_id'), ['run_id'], unique=False)

    op.create_table('citations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_run_id'), ['run_id'], unique=False)

    op.create_table('evidence_claims',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claims_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_claims_verification_status'), ['verification_status'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=96), nullable=False),
    sa.Column('experiment_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('code_artifact_id', sa.String(length=96), nullable=True),
    sa.Column('input_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=24), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_run_id'), ['run_id'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=96), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_run_id'), ['run_id'], unique=False)

    op.create_table('model_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('model_provider', sa.String(length=48), nullable=False),
    sa.Column('model_identifier', sa.String(length=96), nullable=False),
    sa.Column('prompt_version', sa.String(length=48), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_calls_run_id'), ['run_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('competition_profile_id', sa.String(length=64), nullable=True),
    sa.Column('budget_profile', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('current_state_version', sa.Integer(), nullable=False),
    sa.Column('total_cost_estimate', sa.Float(), nullable=False),
    sa.Column('total_runtime_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_state_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'version_number', name='uq_run_version')
    )
    with op.batch_alter_table('run_state_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_state_versions_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_state_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_state_versions_run_id'))

    op.drop_table('run_state_versions')
    op.drop_table('runs')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_calls_run_id'))

    op.drop_table('model_calls')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_run_id'))

    op.drop_table('exports')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_run_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('evidence_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_claims_verification_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_claims_run_id'))

    op.drop_table('evidence_claims')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_run_id'))

    op.drop_table('citations')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoints_run_id'))

    op.drop_table('checkpoints')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    # ### end Alembic commands ###
