"""The 20 seed method records (spec milestone 4 / 16.2 taxonomy).

Each entry is a registered :class:`RetrievedMethod` with the fields required by
spec 16.3. ``pilot_template`` keys into the code-template library (Phase F) so a
strategy built on this method has a runnable pilot.
"""

from __future__ import annotations

from modelforge.schemas.enums import MethodCategory, ProblemFamily
from modelforge.schemas.problem import RetrievedMethod


def _m(**kw: object) -> RetrievedMethod:
    return RetrievedMethod(**kw)  # type: ignore[arg-type]


# A method's relevant problem families, used by retrieval ranking.
METHOD_FAMILIES: dict[str, list[ProblemFamily]] = {}


def _record(families: list[ProblemFamily], **kw: object) -> RetrievedMethod:
    method = _m(**kw)
    METHOD_FAMILIES[method.method_id] = families
    return method


METHODS: list[RetrievedMethod] = [
    # ---------------- prediction ---------------- #
    _record(
        [ProblemFamily.PREDICTION],
        method_id="linear_regression",
        name="Linear Regression",
        category=MethodCategory.PREDICTION,
        summary="Ordinary least squares linear model for continuous targets.",
        use_cases=["trend estimation", "interpretable forecasting", "baseline regression"],
        applicability_conditions=["approximately linear relationship", "tabular numeric features"],
        required_data=["numeric feature columns", "continuous target"],
        assumptions=["linearity", "independent errors", "homoscedasticity"],
        advantages=["interpretable coefficients", "fast", "well understood"],
        limitations=["misses nonlinearity", "sensitive to outliers"],
        failure_modes=["multicollinearity", "extrapolation error"],
        evaluation_metrics=["RMSE", "MAE", "R2"],
        computational_cost="low",
        pilot_template="prediction",
        implementation_template="prediction",
        visualization_templates=["residual_plot", "prediction_vs_actual"],
        references=["Montgomery et al., Introduction to Linear Regression Analysis"],
    ),
    _record(
        [ProblemFamily.PREDICTION],
        method_id="arima",
        name="ARIMA",
        category=MethodCategory.PREDICTION,
        summary="Autoregressive integrated moving-average model for univariate time series.",
        use_cases=["short-horizon forecasting", "stationary series with trend/seasonality"],
        applicability_conditions=["ordered time index", "single target series"],
        required_data=["datetime column", "continuous target"],
        assumptions=["stationarity after differencing"],
        advantages=["principled time-series model", "confidence intervals"],
        limitations=["univariate", "manual order selection", "weak with regime change"],
        failure_modes=["non-stationarity", "insufficient history"],
        evaluation_metrics=["RMSE", "MAE", "MAPE"],
        computational_cost="medium",
        pilot_template="timeseries",
        implementation_template="timeseries",
        visualization_templates=["forecast_plot", "acf_pacf"],
        references=["Box & Jenkins, Time Series Analysis"],
    ),
    _record(
        [ProblemFamily.PREDICTION],
        method_id="exponential_smoothing",
        name="Exponential Smoothing",
        category=MethodCategory.PREDICTION,
        summary="Holt-Winters level/trend/seasonal smoothing for forecasting.",
        use_cases=["seasonal demand forecasting", "smooth trend extrapolation"],
        applicability_conditions=["regular time index", "clear trend or seasonality"],
        required_data=["datetime column", "continuous target"],
        assumptions=["additive or multiplicative seasonality"],
        advantages=["simple", "robust", "fast"],
        limitations=["univariate", "limited covariate use"],
        failure_modes=["abrupt level shifts"],
        evaluation_metrics=["RMSE", "MAE", "MAPE"],
        computational_cost="low",
        pilot_template="timeseries",
        implementation_template="timeseries",
        visualization_templates=["forecast_plot"],
        references=["Hyndman & Athanasopoulos, Forecasting: Principles and Practice"],
    ),
    _record(
        [ProblemFamily.PREDICTION, ProblemFamily.CLASSIFICATION],
        method_id="random_forest",
        name="Random Forest",
        category=MethodCategory.PREDICTION,
        summary="Bagged decision-tree ensemble for regression or classification.",
        use_cases=["nonlinear tabular prediction", "feature-importance analysis"],
        applicability_conditions=["tabular features", "moderate sample size"],
        required_data=["feature columns", "target column"],
        assumptions=["i.i.d. samples"],
        advantages=["captures nonlinearity", "robust to outliers", "feature importance"],
        limitations=["less interpretable", "larger models"],
        failure_modes=["extrapolation beyond training range"],
        evaluation_metrics=["RMSE", "MAE", "Accuracy", "F1"],
        computational_cost="medium",
        pilot_template="prediction",
        implementation_template="prediction",
        visualization_templates=["feature_importance", "prediction_vs_actual"],
        references=["Breiman, Random Forests (2001)"],
    ),
    _record(
        [ProblemFamily.PREDICTION, ProblemFamily.CLASSIFICATION],
        method_id="gradient_boosting",
        name="Gradient Boosting (XGBoost-compatible)",
        category=MethodCategory.PREDICTION,
        summary="Boosted tree ensemble via sklearn HistGradientBoosting (XGBoost-compatible).",
        use_cases=["high-accuracy tabular prediction", "competitions"],
        applicability_conditions=["tabular features", "enough data to avoid overfitting"],
        required_data=["feature columns", "target column"],
        assumptions=["i.i.d. samples"],
        advantages=["strong accuracy", "handles mixed features"],
        limitations=["tuning sensitive", "less interpretable"],
        failure_modes=["overfitting with small data"],
        evaluation_metrics=["RMSE", "MAE", "Accuracy", "AUC"],
        computational_cost="medium",
        pilot_template="prediction",
        implementation_template="prediction",
        visualization_templates=["feature_importance"],
        references=["Chen & Guestrin, XGBoost (2016)"],
    ),
    # ---------------- optimization ---------------- #
    _record(
        [ProblemFamily.OPTIMIZATION],
        method_id="linear_programming",
        name="Linear Programming",
        category=MethodCategory.OPTIMIZATION,
        summary="Optimize a linear objective subject to linear constraints (via PuLP/CBC).",
        use_cases=["resource allocation", "blending", "transportation"],
        applicability_conditions=["linear objective and constraints", "continuous variables"],
        required_data=["cost/benefit coefficients", "constraint matrix"],
        assumptions=["linearity", "divisible decisions"],
        advantages=["globally optimal", "fast", "mature solvers"],
        limitations=["no integrality", "linearity required"],
        failure_modes=["infeasible/unbounded models"],
        evaluation_metrics=["objective_value", "constraint_satisfaction"],
        computational_cost="low",
        pilot_template="optimization",
        implementation_template="optimization",
        visualization_templates=["allocation_bar"],
        references=["Dantzig, Linear Programming and Extensions"],
    ),
    _record(
        [ProblemFamily.OPTIMIZATION],
        method_id="integer_programming",
        name="Integer Programming",
        category=MethodCategory.OPTIMIZATION,
        summary="Linear optimization with integer/binary decision variables (PuLP/CBC).",
        use_cases=["assignment", "scheduling", "facility location", "knapsack"],
        applicability_conditions=["discrete decisions", "linear objective/constraints"],
        required_data=["coefficients", "constraints", "variable bounds"],
        assumptions=["linearity with integrality"],
        advantages=["models discrete decisions", "optimal within tolerance"],
        limitations=["NP-hard", "can be slow at scale"],
        failure_modes=["combinatorial blow-up", "infeasibility"],
        evaluation_metrics=["objective_value", "optimality_gap"],
        computational_cost="medium",
        pilot_template="optimization",
        implementation_template="optimization",
        visualization_templates=["allocation_bar"],
        references=["Wolsey, Integer Programming"],
    ),
    _record(
        [ProblemFamily.OPTIMIZATION],
        method_id="dynamic_programming",
        name="Dynamic Programming",
        category=MethodCategory.OPTIMIZATION,
        summary="Optimal substructure decomposition for sequential decisions.",
        use_cases=["shortest path on DAGs", "knapsack", "inventory control"],
        applicability_conditions=["optimal substructure", "overlapping subproblems"],
        required_data=["state/transition definition", "stage rewards"],
        assumptions=["Markov decomposition"],
        advantages=["exact for well-posed problems"],
        limitations=["state-space explosion"],
        failure_modes=["large continuous state spaces"],
        evaluation_metrics=["objective_value"],
        computational_cost="medium",
        pilot_template="optimization",
        implementation_template="optimization",
        visualization_templates=["value_function"],
        references=["Bellman, Dynamic Programming"],
    ),
    _record(
        [ProblemFamily.OPTIMIZATION],
        method_id="genetic_algorithm",
        name="Genetic Algorithm",
        category=MethodCategory.OPTIMIZATION,
        summary="Population-based metaheuristic for non-convex/black-box optimization.",
        use_cases=["non-convex objectives", "combinatorial search", "tuning"],
        applicability_conditions=["evaluable objective", "encodable solutions"],
        required_data=["objective function", "variable ranges"],
        assumptions=["objective comparability"],
        advantages=["handles non-convexity", "no gradients needed"],
        limitations=["no optimality guarantee", "tuning needed"],
        failure_modes=["premature convergence"],
        evaluation_metrics=["best_objective", "convergence_curve"],
        computational_cost="medium",
        pilot_template="optimization",
        implementation_template="optimization",
        visualization_templates=["convergence_curve"],
        references=["Holland, Adaptation in Natural and Artificial Systems"],
    ),
    _record(
        [ProblemFamily.OPTIMIZATION],
        method_id="simulated_annealing",
        name="Simulated Annealing",
        category=MethodCategory.OPTIMIZATION,
        summary="Probabilistic metaheuristic escaping local optima via cooling schedule.",
        use_cases=["combinatorial optimization", "layout", "routing"],
        applicability_conditions=["evaluable objective", "neighborhood operator"],
        required_data=["objective function", "initial solution"],
        assumptions=["meaningful neighbor moves"],
        advantages=["simple", "escapes local optima"],
        limitations=["no guarantee", "schedule sensitive"],
        failure_modes=["poor cooling schedule"],
        evaluation_metrics=["best_objective", "convergence_curve"],
        computational_cost="medium",
        pilot_template="optimization",
        implementation_template="optimization",
        visualization_templates=["convergence_curve"],
        references=["Kirkpatrick et al., Optimization by Simulated Annealing"],
    ),
    # ---------------- evaluation ---------------- #
    _record(
        [ProblemFamily.EVALUATION],
        method_id="entropy_weight",
        name="Entropy Weight Method",
        category=MethodCategory.EVALUATION,
        summary="Objective indicator weighting from information entropy of each criterion.",
        use_cases=["multi-criteria weighting", "composite indices"],
        applicability_conditions=["multiple comparable indicators"],
        required_data=["indicator matrix (alternatives x criteria)"],
        assumptions=["criteria measured on comparable scales after normalization"],
        advantages=["objective weights", "no subjective input"],
        limitations=["ignores expert preference"],
        failure_modes=["degenerate when an indicator is constant"],
        evaluation_metrics=["weight_vector"],
        computational_cost="low",
        pilot_template="evaluation",
        implementation_template="evaluation",
        visualization_templates=["weight_bar"],
        references=["Shannon, A Mathematical Theory of Communication"],
    ),
    _record(
        [ProblemFamily.EVALUATION],
        method_id="topsis",
        name="TOPSIS",
        category=MethodCategory.EVALUATION,
        summary="Rank alternatives by distance to ideal and anti-ideal solutions.",
        use_cases=["multi-criteria decision ranking"],
        applicability_conditions=["weighted criteria", "numeric indicator matrix"],
        required_data=["indicator matrix", "criteria weights", "benefit/cost direction"],
        assumptions=["monotonic preference per criterion"],
        advantages=["intuitive geometry", "full ranking"],
        limitations=["sensitive to normalization/weights"],
        failure_modes=["rank reversal"],
        evaluation_metrics=["closeness_coefficient", "ranking"],
        computational_cost="low",
        pilot_template="evaluation",
        implementation_template="evaluation",
        visualization_templates=["ranking_bar"],
        references=["Hwang & Yoon, Multiple Attribute Decision Making"],
    ),
    _record(
        [ProblemFamily.EVALUATION, ProblemFamily.CLUSTERING],
        method_id="pca",
        name="Principal Component Analysis",
        category=MethodCategory.EVALUATION,
        summary="Linear dimensionality reduction onto orthogonal variance-maximizing axes.",
        use_cases=["dimensionality reduction", "index construction", "visualization"],
        applicability_conditions=["correlated numeric features"],
        required_data=["numeric feature matrix"],
        assumptions=["linear structure", "variance is meaningful"],
        advantages=["decorrelates", "compresses"],
        limitations=["components less interpretable"],
        failure_modes=["nonlinear structure missed"],
        evaluation_metrics=["explained_variance_ratio"],
        computational_cost="low",
        pilot_template="evaluation",
        implementation_template="evaluation",
        visualization_templates=["scree_plot", "biplot"],
        references=["Jolliffe, Principal Component Analysis"],
    ),
    # ---------------- simulation ---------------- #
    _record(
        [ProblemFamily.SIMULATION],
        method_id="monte_carlo",
        name="Monte Carlo Simulation",
        category=MethodCategory.SIMULATION,
        summary="Estimate distributions/expectations by repeated random sampling.",
        use_cases=["risk analysis", "uncertainty propagation", "integration"],
        applicability_conditions=["sampleable input distributions"],
        required_data=["input distributions", "system model"],
        assumptions=["valid input distributions"],
        advantages=["flexible", "handles complex systems"],
        limitations=["variance ~ 1/sqrt(N)", "compute cost"],
        failure_modes=["biased input distributions"],
        evaluation_metrics=["estimate_mean", "estimate_std", "confidence_interval"],
        computational_cost="medium",
        pilot_template="simulation",
        implementation_template="simulation",
        visualization_templates=["distribution_hist"],
        references=["Metropolis & Ulam, The Monte Carlo Method"],
    ),
    # ---------------- graph ---------------- #
    _record(
        [ProblemFamily.GRAPH],
        method_id="shortest_path",
        name="Shortest Path",
        category=MethodCategory.GRAPH,
        summary="Minimum-cost path between nodes (Dijkstra / Bellman-Ford via networkx).",
        use_cases=["routing", "network distance", "logistics"],
        applicability_conditions=["weighted graph"],
        required_data=["edge list with weights"],
        assumptions=["non-negative weights for Dijkstra"],
        advantages=["exact", "fast"],
        limitations=["negative cycles break Dijkstra"],
        failure_modes=["disconnected source/target"],
        evaluation_metrics=["path_length", "path_cost"],
        computational_cost="low",
        pilot_template="graph",
        implementation_template="graph",
        visualization_templates=["graph_path"],
        references=["Dijkstra, A Note on Two Problems in Connexion with Graphs"],
    ),
    _record(
        [ProblemFamily.GRAPH],
        method_id="max_flow",
        name="Maximum Flow",
        category=MethodCategory.GRAPH,
        summary="Maximum feasible flow from source to sink (Edmonds-Karp via networkx).",
        use_cases=["capacity planning", "bipartite matching", "network reliability"],
        applicability_conditions=["capacitated directed graph"],
        required_data=["edge list with capacities", "source", "sink"],
        assumptions=["flow conservation"],
        advantages=["exact", "well-studied"],
        limitations=["single commodity"],
        failure_modes=["no s-t path"],
        evaluation_metrics=["max_flow_value"],
        computational_cost="low",
        pilot_template="graph",
        implementation_template="graph",
        visualization_templates=["graph_flow"],
        references=["Ford & Fulkerson, Flows in Networks"],
    ),
    _record(
        [ProblemFamily.GRAPH],
        method_id="centrality",
        name="Centrality Analysis",
        category=MethodCategory.GRAPH,
        summary="Rank node importance (degree, betweenness, eigenvector via networkx).",
        use_cases=["influence ranking", "critical-node detection"],
        applicability_conditions=["graph structure available"],
        required_data=["edge list"],
        assumptions=["edges encode relevant relations"],
        advantages=["multiple notions of importance"],
        limitations=["measure choice matters"],
        failure_modes=["disconnected graphs distort some measures"],
        evaluation_metrics=["centrality_scores"],
        computational_cost="medium",
        pilot_template="graph",
        implementation_template="graph",
        visualization_templates=["centrality_bar"],
        references=["Freeman, Centrality in Social Networks"],
    ),
    # ---------------- clustering ---------------- #
    _record(
        [ProblemFamily.CLUSTERING],
        method_id="kmeans",
        name="K-Means Clustering",
        category=MethodCategory.CLUSTERING,
        summary="Partition samples into k variance-minimizing clusters.",
        use_cases=["segmentation", "vector quantization"],
        applicability_conditions=["numeric features", "roughly spherical clusters"],
        required_data=["numeric feature matrix"],
        assumptions=["clusters of similar scale/variance"],
        advantages=["simple", "scalable"],
        limitations=["needs k", "sensitive to scale/outliers"],
        failure_modes=["non-convex clusters"],
        evaluation_metrics=["silhouette", "inertia"],
        computational_cost="low",
        pilot_template="clustering",
        implementation_template="clustering",
        visualization_templates=["cluster_scatter"],
        references=["MacQueen, Some Methods for Classification"],
    ),
    _record(
        [ProblemFamily.CLUSTERING],
        method_id="dbscan",
        name="DBSCAN",
        category=MethodCategory.CLUSTERING,
        summary="Density-based clustering that finds arbitrary shapes and flags noise.",
        use_cases=["anomaly-aware clustering", "spatial clusters"],
        applicability_conditions=["meaningful density", "tunable eps"],
        required_data=["numeric feature matrix"],
        assumptions=["clusters are dense regions"],
        advantages=["no k", "detects noise", "arbitrary shapes"],
        limitations=["eps sensitive", "varying densities hard"],
        failure_modes=["poor eps choice"],
        evaluation_metrics=["silhouette", "n_clusters", "n_noise"],
        computational_cost="medium",
        pilot_template="clustering",
        implementation_template="clustering",
        visualization_templates=["cluster_scatter"],
        references=["Ester et al., DBSCAN (1996)"],
    ),
    _record(
        [ProblemFamily.CLUSTERING],
        method_id="hierarchical_clustering",
        name="Hierarchical Clustering",
        category=MethodCategory.CLUSTERING,
        summary="Agglomerative clustering producing a dendrogram of nested groups.",
        use_cases=["taxonomy discovery", "small-sample segmentation"],
        applicability_conditions=["distance metric defined"],
        required_data=["numeric feature matrix"],
        assumptions=["meaningful linkage criterion"],
        advantages=["no preset k", "interpretable dendrogram"],
        limitations=["O(n^2) memory", "greedy"],
        failure_modes=["large datasets"],
        evaluation_metrics=["silhouette", "cophenetic_corr"],
        computational_cost="medium",
        pilot_template="clustering",
        implementation_template="clustering",
        visualization_templates=["dendrogram"],
        references=["Ward, Hierarchical Grouping"],
    ),
    # ---------------- classification ---------------- #
    _record(
        [ProblemFamily.CLASSIFICATION],
        method_id="logistic_regression",
        name="Logistic Regression",
        category=MethodCategory.CLASSIFICATION,
        summary="Linear classifier modeling log-odds; interpretable probabilities.",
        use_cases=["binary/multiclass classification", "interpretable baseline"],
        applicability_conditions=["roughly linear decision boundary in feature space"],
        required_data=["feature columns", "categorical target"],
        assumptions=["log-linear odds"],
        advantages=["interpretable", "probabilistic", "fast"],
        limitations=["linear boundary"],
        failure_modes=["nonlinear separation", "class imbalance"],
        evaluation_metrics=["Accuracy", "F1", "AUC"],
        computational_cost="low",
        pilot_template="classification",
        implementation_template="classification",
        visualization_templates=["roc_curve", "confusion_matrix"],
        references=["Hosmer & Lemeshow, Applied Logistic Regression"],
    ),
    _record(
        [ProblemFamily.CLASSIFICATION],
        method_id="decision_tree",
        name="Decision Tree",
        category=MethodCategory.CLASSIFICATION,
        summary="Recursive axis-aligned splits; highly interpretable classifier/regressor.",
        use_cases=["interpretable rules", "nonlinear baseline"],
        applicability_conditions=["tabular features"],
        required_data=["feature columns", "target column"],
        assumptions=["axis-aligned splits suffice"],
        advantages=["interpretable", "handles mixed features"],
        limitations=["overfits without pruning"],
        failure_modes=["high variance"],
        evaluation_metrics=["Accuracy", "F1"],
        computational_cost="low",
        pilot_template="classification",
        implementation_template="classification",
        visualization_templates=["tree_plot", "confusion_matrix"],
        references=["Breiman et al., Classification and Regression Trees"],
    ),
]
