"""CodeAuthorAgent (spec 8.7).

The LLM only SELECTS a template + concrete model kind; the actual executable
code is produced deterministically by the CodeGenerator. This guarantees every
quantitative report artifact is generated by real, runnable code (spec 8.7
invariant) and keeps generation reproducible and testable without an LLM.
"""

from __future__ import annotations

from pydantic import Field

from modelforge.agents.base import AgentContext, AgentResult, BaseAgent
from modelforge.schemas.base import MFBaseModel
from modelforge.schemas.experiment import CodeArtifact
from modelforge.schemas.strategy import StrategyCandidate
from modelforge.services.codegen import CodeGenerator


class CodeAuthorSelection(MFBaseModel):
    template: str
    model_kind: str = ""
    notes: str = Field(default="")


class CodeAuthorAgent(BaseAgent[CodeAuthorSelection]):
    agent_key = "code_author"
    output_schema = CodeAuthorSelection

    def __init__(self, ctx: AgentContext, generator: CodeGenerator | None = None) -> None:
        super().__init__(ctx)
        self.generator = generator or CodeGenerator()

    def author(self, strategy: StrategyCandidate) -> AgentResult[CodeArtifact]:
        primary_method = (
            strategy.method_stack[0].method_id if strategy.method_stack else ""
        )
        context = {
            "problem_family": strategy.problem_family.value,
            "template": strategy.pilot_template,
            "model_kind": primary_method,
        }
        selection = self.run_structured(context, temperature=0.0)
        if not selection.ok or selection.output is None:
            # Fall back to deterministic choice from the strategy itself.
            template = strategy.pilot_template or strategy.problem_family.value
            model_kind = primary_method
        else:
            template = selection.output.template or strategy.pilot_template
            model_kind = selection.output.model_kind or primary_method

        code = self.generator.generate(
            strategy.strategy_id, template, strategy.problem_family, model_kind=model_kind
        )
        return AgentResult(output=code)
